spring:
  datasource:
    url: jdbc:h2:file:~/ucms;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # keeps schema in sync with your entities
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
